### ISSUE TITLE
Business rules bugs with population_count verification on locationspecies POST

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices#532]
For detail , see: https://github.com/USGS-WiM/whispers/issues/1250

#### Bugs:

1. POST to /api/locationspecies/{id}/ allows `population_count` to be less than `dead_count`, `dead_count_estimated`, `sick_count`, `sick_count_estimated`

     expected behavior: should be prevented per business rules

2.  POST to /api/locationspecies/{id}/ throws error if `population_count` is null when there is any sum greater than 0 among `dead_count`, `dead_count_estimated`, `sick_count`, `sick_count_estimated`

       expected behavior: should be allowed per business rules (tentative - awaitng NWHC confirmation)

**Comment by aaronstephenson** [comment]
Fixed in c10854ef, pushed to test environment. @JChipault take a look and let me know if and when to push to production.

**Comment by JChipault** [comment]
I'm getting a JSON error message.

I created an event with null population (171067) and then I went to the event details page and tried to make the population less than the known dead and got this error
![image](https://user-images.githubusercontent.com/49287076/150015716-b6d13416-d01c-4c30-9c40-200cc27277f8.png)

I was expecting an error message, but was hoping for one that would tell the user what needs to be changed.

Furthermore, when I tried to make the population higher than the known dead (3), I still got the same JSON error message. In this scenario, since the population was greater than the sick+dead, I was expecting to be able to "save changes" without a hitch

**Comment by aaronstephenson** [comment]
In the browser's dev tools when you open to the Network tab you can see the response from the API, and when you click on the line with the error, it shows you the error code (500) and the error message:
```
TypeError at /locationspecies/298667/
'<=' not supported between instances of 'NoneType' and 'NoneType'
```

I see what happened. When I was testing my bug fix locally I only used a scenario where the 4 dead/sick fields were populated, and only tried different values for population, so I didn't come across the scenario you're reporting. In your scenario, the API is trying to compare two nulls with a math operator and it can't do that.

This is a quick fix.

**Comment by aaronstephenson** [comment]
Fixed in afa10984 and pushed to test environment. @JChipault please test this again when you have a moment.

**Comment by JChipault** [comment]
Closer. With 2 dead, I can't have a population of 1, so that's good and working as expected now. However, I can still have a population of 0. When I try to enter a negative number, I get a red warning message that the "minimum value is 0"... can we make the minimum value as 1? Since population is defined as healthy+sick+dead and the user always has to have at least 1 sick or dead when they complete an event, then the population would always have to be 1 or more.

![image](https://user-images.githubusercontent.com/49287076/150025975-d67463b1-b5ba-4079-bac8-5815b44e1643.png)

Just to confirm the business rules were working for numbers of sick and dead, I tried to mark an event complete that had a species that was null all the way across on the sick and dead counts and got this (which was good and what I expected and confirms to me that the population should always be 1 or more):
"For morbidity/mortality events marked as Complete, there must be at least one value greater than 0 between Known Dead, Estimated Dead, Known Sick, and Estimated Sick for all species in the event."

**Comment by aaronstephenson** [comment]
Fixed in eb689885 and pushed to test environment, please try this again when you have a moment.

So the problem here isn't my misreading of the business rules, but a feature of python (that I momentarily forgot earlier this afternoon) where the value `0` evaluates to `False`. So the population count validation is being skipped over for this newest scenario:
```
if pop_count and pop_count < (any_dead_count + any_sick_count):
    pop_is_valid = False
```

I don't think it is necessary for the population count field to have a minimum of 1. The fix for this `0` == `False` issue makes forcing a minimum value of 1 moot, I think; the business rules (should) already be taking care of that scenario because 0 is always less than any one value of the four dead/sick counts and so the user will be warned, without the need for setting a minimum of 1.

**Comment by JChipault** [comment]
Cool. That gets us a long way! Let's call it there.

It's still possible to enter a 0 in population for an event that isn't complete and that doesn't make sense, but I think we at NWHC should evaluate more how this links to the sick/dead count so I'm going to table the rest of this until we jump into more usability development later this year.

For now, this is a big improvement and gets rid of the bug of not being able to null the field! Thanks!

**Comment by aaronstephenson** [comment]
@JChipault do you want me to push this fix to production?

Also, I cannot recreate this, either locally in my dev environment or the test environment:
>It's still possible to enter a 0 in population for an event that isn't complete

Whenever I try to add a new species with a population count of `0` I get the expected validation error message
>"New location_species population_count cannot be less than the sum of dead_count and sick_count (where those counts are the maximum of the estimated or known count)."

Can you tell me how you were able to enter 0 so I can try to replicate it? Thanks.

**Comment by aaronstephenson** [comment]
@JChipault Can you tell me more about how you were able to enter a 0 for population count? I cannot recreate it.

**Comment by JChipault** [comment]
This was the third thing on my to do list today and I thought for sure it'd get done but I only just finished item 2 on my list... this is tops tomorrow. Sorry to keep you hanging.

**Comment by JChipault** [comment]
Go to an incomplete event, add a species, put in population of 0, don't put any numbers for sick or dead (sick and dead numbers aren't required for every species until you try to mark an event as complete). It will allow you to save a species with population of zero. 

If you do these same steps and add a negative number for population instead of a 0, then you get a red warning that "minimum value is 0"... how easy is it to change to min value of 1?

When you go back and try to edit that species and add in sick or dead numbers, which you would have to do in order to "complete" an event, then you (appropriately) get the error message about population having to be greater.

**Comment by aaronstephenson** [comment]
Thanks @JChipault! I hadn't ever attempted a scenario with only the population_count field populated but not any others. 🤦‍♂️ Thanks for finding that. I made the fix in 546b74ae and will include it in my next release.

**Comment by aaronstephenson** [comment]
Fix deployed in test and production environments as v2.1.11 0e85d7f
