### ISSUE TITLE
"Undetermined" event diagnosis doesn't always stick

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices#547]
NOTE: this could be a big lift... we're not sure. Take a gander below and let us know how much time this might take before you jump in. Currently, our internal users know to manually enter the disappearing "Undetermined" back in to the record as needed, so that's our work around.

**Describe the bug**
Sometimes "Undetermined" is selected as an event level diagnosis manually but it doesn't stick there. 

**To Reproduce**
I've done some playing around on the test site and these are the scenarios I have found wherein the "Undetermined" that I select for event diagnosis doesn't seem to stick:

Open up an incomplete event that has “Pending” event diagnosis (without or without any species diagnoses). 

Select event diagnosis of “Undetermined” 

“Undetermined” replaces “Pending”, as expected 

Edit some types of location information (e.g., add species diagnosis (something other than “Undetermined”), update number dead, or add an end date, etc)... event diagnosis flips back to “Pending”. [Though you can add a location comment without causing the "Undetermined" to disappear]

or

Edit some types of event information (e.g., visibility)... event diagnosis flips back to "Pending"

or

If you toggle to "complete" and then back to "incomplete"... event diagnosis flips back to "Pending"

It seems that this flipping back to "Pending" happens even if there is a species diagnosis of "Undetermined".

If you have another event diagnosis (e.g., Highly Pathogenic Avian Influenza) along with the "Undetermined" event diagnosis, then the "Undetermined" doesn't flip back to "Pending" in the above scenarios, it just disappears, leaving only your Avian Influenza event diagnosis.

**Expected behavior**
If you manually select "Undetermined" as an event diagnosis then you want it to stay there.

Or, put another way...

Only want to see "Pending" if nothing is else has been selected for an event diagnosis and the event is "Incomplete"

**Comment by JChipault** [comment]
Although I just tried an event on the test site that did not have undetermined at the species or event level... it did have "tularemia" at the event level already... then I added undetermined to the species level... then I selected undetermined at the event level... and then I edited the number of dead for a species in the event... and then "undetermined" at the event level disappeared on me, even though it was still listed at the species level.

**Comment by BlakeDraper** [comment]
@aaronstephenson ☝️ interesting find there from Jenny.

**Comment by aaronstephenson** [comment]
@nbaertlein @JChipault

I spent a good chunk of time looking into this and here's what I found...

Just for background, to help with understanding the rest of what I write below, the business rules (as found in the spreadsheet in our joint SharePoint folder) for EventDiagnoses.diagnosis are

> Diagnosis from species_diagnosis table will be inserted here if diagnosis deemed an event-level diagnosis. 
> 
> If no event-level diagnosis indicated by user, then event diagnosis of "Pending" used for ongoing investigations (when "Complete"=0) and "Undetermined" used as event-level diagnosis_id if investigation is complete ("Complete"=1). 
> 
> If have "Undetermined" at the event level, should have no other diagnoses at event level.

My interpretation of that was:
A. If no event-level diagnosis indicated by user and the event is incomplete, the Event Diagnosis _must_ be "Pending"
B. If no event-level diagnosis indicated by user and the event is complete, the Event Diagnosis _must_ be "Undetermined"
C. If there is an existing Event Diagnosis and it is "Undetermined", there can be no other Event Diagnosis, so any others must be rejected or deleted.

... and of course, despite this interpretation, the implementation was still buggy

What I'm understanding from what you have written above in this issue, you instead want the following:
A. If no event-level diagnosis indicated by user and the event is incomplete, the Event Diagnosis _must_ be "Pending", **_however, a user can manually change this to Undetermined_** (in other words, it's OK to have an incomplete event with an "Undetermined" Event Diagnosis, if that's the user's intent).
B. If no event-level diagnosis indicated by user and the event is complete, the Event Diagnosis _must_ be "Undetermined"
C. If there is an existing Event Diagnosis and it is "Undetermined" **_and a user creates another Event Diagnosis for the same event, the existing "Undetermined" must be deleted_**.

For the most part, that won't be difficult at all to implement, but I do have a what-if scenario:
What if there's a situation where an event already has a 'regular' Event Diagnosis (say, "Tularemia"), and a user creates another Event Diagnosis for that same event and it is "Undetermined", what should be done? Do we accept the new "Undetermined" and delete "Tularemia", or do we reject the new "Undetermined"?

**Comment by JChipault** [comment]
Thanks for talking this through, Aaron. We've evolved our thinking about C since first writing the business rules and it can be ignored now. So both Tularemia and Undetermined at the event level would be ok for either an incomplete or a complete event. My apologies for not checking that spreadsheet before adding this github ticket to make sure it was clear in the spreadsheet. You can see that I made a comment in 2020 that C wasn't coded in the site when I combed through that spreadsheet noting differences between initial business rules and how the site was performing, but unsaid in that spreadsheet is that that's ok that it's not coded in. Good news is that I think you have interpretation of A and B spot on so perhaps we're good to go now.

**Comment by aaronstephenson** [comment]
Fixed in a6351c3, will be included soon in next Test branch release.

**Comment by JChipault** [comment]
Quick test put me at a dead end... I found an incomplete event with "Pending" as event dx. I was a read/write collaborate on this event (171071) in my "Jenny Partner" account. I selected event diagnosis of "Undetermined" and then saw both "Pending" and "Undetermined" listed and the delete icon by both of them became greyed out (even though the event is still incomplete). And the delete icon by event organization also greyed out. I was expecting "Undetermined" to replace "Pending" and the delete icon to be active.

**Comment by JChipault** [comment]
For some reason, github is not letting me upload an image. Will try again tomorrow. Clocking out

**Comment by JChipault** [comment]
Got back to this today and went to a different event (171053) with a pending diagnosis that I can access in my "Jenny Partner" account, and before I could do any action, the buttons were already greyed out (looks like github will let me attach a picture today). But I figured out why... likely because I'm a read/write collaborator on these events from this account so I can't delete anything. Will keep testing with a better set up and get back to you. 
![image](https://user-images.githubusercontent.com/49287076/179281548-d7fb9642-d2db-45c3-83e4-4051a47bf581.png)

**Comment by JChipault** [comment]
Ok, looks like "Undetermined" is now sticking fine when it is selected by the user (hooray!) but it's not replacing the "Pending". We see "Pending" as just the placeholder until anything else (including "Undetermined") is selected OR until the event is switched from "incomplete" to "complete"... will test that next.... 
![image](https://user-images.githubusercontent.com/49287076/179282760-c0e81d4c-b3c9-46fd-ba93-88358f248499.png)

Ok, when an event is flipped from "incomplete" to "complete" on the test site without any event diagnosis selected at all, the "Pending" isn't being replaced automatically by "Undetermined". 
![image](https://user-images.githubusercontent.com/49287076/179283008-b2f76f8a-d64c-498c-85a2-77594ce4b8d7.png)

So looks like "Pending" is hanging around a bit too much now.

**Comment by aaronstephenson** [comment]
Well, the API is _supposed_ to be doing that flipping when an event is set to Complete. I am not very familiar with using the web client, does this happen before or after you click the Save button?

**Comment by JChipault** [comment]
Upon re-reading, I think my wording in my last post isn't great... I'm trying to point out 2 scenarios (that go with the 2 screenshots) where the "Pending" should disappear:
1) when the user selects "Undetermined" (or any other event diagnosis) in an incomplete event
2) when an "incomplete" event with "Pending" is switched to "complete"

Regarding your question (for scenario 2), after you hit the "save" button in the subform that has "WHISPers Record Status" field that you've set to "Complete", then the event reloads and the "Pending" is gone and "Undetermined" takes its place (assuming no other event diagnosis was selected by the user).

**Comment by aaronstephenson** [comment]
Thanks Jenny. So what you're saying sounds to me like it's front-end stuff, or at the very least a misunderstanding between us about the exact moment when these changes need to happen (immediately in the front end, or in the back end after hitting save). @BlakeDraper what are your thoughts?

Closely reading your last sentence, it sounds like if there are existing event diagnoses then "Pending" doesn't get removed and replaced by "Undetermined"? I'm looking at my code and seeing where that is happening. I can push up a tweak to solve that right away.

**Comment by JChipault** [comment]
"Pending" should only show if nothing else is selected as an event diagnosis by the user AND the event is incomplete. Does communicating it that way help? Sorry, I'm not very articulate today. 

And I don't think there is a "Pending" option in the table (I think it's just coded on the front end) so it would make sense to me that perhaps there needs to be some client updating to account for the new backend flow.

**Comment by JChipault** [comment]
The "Pending" is working fine on the live site if that's of any help.

**Comment by aaronstephenson** [comment]
Thanks Jenny, yes that has been my understanding of how "Pending" works. I'm just getting confused by the rest of what you're writing. It really sounds to me like we have a misunderstanding about the exact moment changes should appear in the web client. All the business rule logic here happens in the back-end, but that only gets triggered when the Save button is clicked. Maybe it would help to talk on the phone or a video chat?

**Comment by aaronstephenson** [comment]
I just pushed a fix 926fea18 to the Test environment and tested a few scenarios and it looks good to me, give it a try and let me know what you find.

**Comment by JChipault** [comment]
Yup, that's super close. Only unexpected behavior I'm still seeing on the test site is at the end of this string.... on the test site currently, if I have an incomplete event that says "Pending" for event diagnosis, then I toggle the event from "incomplete" to "complete", then "Undetermined" replaces "Pending" (good!), then I toggle the event from "complete" back to "incomplete", and "Undetermined" stays (I expect that since I never manually selected "Undetermined" on this event, that it would default back to "Pending" when I go back to "Incomplete"). 

I expect to be able to get an "Undetermined" diagnosis two ways - either I A) manually select it from the dropdown list or B) it autopopulates when I flip an event from "incomplete" to "complete" (and no other event diagnoses has been selected). A and B are both pathways to "Undetermined" on the test site currently and that's good. However, for an event that I toggle from "complete" back to "incomplete", I'd expect that if I manually selected "Undetermined" (scenario A), that "Undetermined" would stick when the event is back at "incomplete", but for scenario B where "undetermined" autopopulated, then I expect the event diagnosis to say "pending" again when I go back to "incomplete".

I see you both clocked out for the day (happy Friday!). Neil and/or Kim can help with this next week while I'm out.

**Comment by BlakeDraper** [comment]
@JChipault I agree with Aaron here. As a half measure of sorts we could simply swap any Undetermined event diagnosis to Pending when an event is switched from Complete to Incomplete. But this would not cover the scenario where the User had manually selected "Undetermined" and we want it to remain. As Aaron says, we have no way of differentiating between a manual selection of Undetermined and an automated selection of undetermined without altering the data schema to include some indication of that.

**Comment by JChipault** [comment]
I'm back from leave and think doing what Blake says above ("As a half measure of sorts we could simply swap any Undetermined event diagnosis to Pending when an event is switched from Complete to Incomplete.") sounds like a good place to leave it for now. 

In summary, looking back at my original "To Reproduce" section for this ticket, it seems we would then have improved two of the three scenarios that were problematic (those two being updating location information and updating event information now will not make the "Undetermined" disappear). That's a pretty substantial improvement. Thanks!

**Comment by BlakeDraper** [comment]
66% of the time it works every time!

**Comment by aaronstephenson** [comment]
In a Teams chat Neil had a proposal for this:

> When the event diagnosis is set automatically per a business rule (which is happening already in certain cases) - set the 'last modified by' field to an 'admin', or 'system' user? Subsequently checking for that user is a way we could possibly know if the event diagnosis was set automatically or manually, without any major change.

And that would certainly work. I think think of some edge cases where this could cause confusion, but overall it seems like a good stopgap measure. What are your thoughts?

**Comment by JChipault** [comment]
I dig it

**Comment by aaronstephenson** [comment]
This new business rule is now implemented in aa02c174 and has been deployed to the test environment. @JChipault give it a try and let us know how it goes.

**Comment by JChipault** [comment]
Yes! Looks great! Thank you so much!

**Comment by aaronstephenson** [comment]
Let me know when you want this promoted to production.

**Comment by JChipault** [comment]
Let's work on pushing things to live next week; feels risky on a Friday.

**Comment by aaronstephenson** [comment]
Included in production v2.2.0 3c81864
